export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const MESSAGE_HIDE = 'MESSAGE_HIDE';
export const ERROR_SHOW = 'ERROR_SHOW';
export const ERROR_HIDE = 'ERROR_HIDE';

export const USER_LOAD_INFO = 'USER_LOAD_INFO';
export const USER_REVOKE = 'USER_REVOKE';

export const DEVIATIONS_CHANGE_TITLE = 'DEVIATIONS_CHANGE_TITLE';
export const DEVIATIONS_CHANGE_PUBLISHED_TIME_BEGIN = 'DEVIATIONS_CHANGE_PUBLISHED_TIME_BEGIN';
export const DEVIATIONS_CHANGE_PUBLISHED_TIME_END = 'DEVIATIONS_CHANGE_PUBLISHED_TIME_END';
export const DEVIATIONS_CHANGE_SORT_FIELD = 'DEVIATIONS_CHANGE_SORT_FIELD';
export const DEVIATIONS_CHANGE_SORT_ORDER = 'DEVIATIONS_CHANGE_SORT_ORDER';
export const DEVIATIONS_CHANGE_TIMESTAMP_BEGIN = 'DEVIATIONS_CHANGE_TIMESTAMP_BEGIN';
export const DEVIATIONS_CHANGE_TIMESTAMP_END = 'DEVIATIONS_CHANGE_TIMESTAMP_END';
export const DEVIATIONS_BROWSE = 'DEVIATIONS_BROWSE';
export const DEVIATIONS_DETAILS_SET_ID = 'DEVIATIONS_DETAILS_SET_ID';
export const DEVIATIONS_DETAILS_SET_DATA = 'DEVIATIONS_DETAILS_SET_DATA';
