export const TOGGLE_MENU = 'TOGGLE_MENU';
export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const MESSAGE_HIDE = 'MESSAGE_HIDE';
export const ERROR_SHOW = 'ERROR_SHOW';
export const CLEAR_LOADED_DATA = 'CLEAR_LOADED_DATA';
export const LOCK_TOGGLE = 'LOCK_TOGGLE';

export const REVOKE = 'REVOKE';

export const USER_LOAD_INFO = 'USER_LOAD_INFO';

export const DEVIATIONS_COMMON_TOGGLE_SELECTION = 'DEVIATIONS_COMMON_TOGGLE_SELECTION';

export const DEVIATIONS_BROWSE_CHANGE_FORM_FIELD_VALUES = 'DEVIATIONS_BROWSE_CHANGE_FORM_FIELD_VALUES';
export const DEVIATIONS_BROWSE_LOAD_PAGE = 'DEVIATIONS_BROWSE_LOAD_PAGE';

export const DEVIATIONS_DETAILS_SET_ID = 'DEVIATIONS_DETAILS_SET_ID';
export const DEVIATIONS_DETAILS_CHANGE_FORM_FIELD_VALUES = 'DEVIATIONS_DETAILS_CHANGE_FORM_FIELD_VALUES';
export const DEVIATIONS_DETAILS_LOAD_DATA = 'DEVIATIONS_DETAILS_LOAD_DATA';
export const DEVIATIONS_DETAILS_LOAD_METADATA = 'DEVIATIONS_DETAILS_LOAD_METADATA';
export const DEVIATIONS_DETAILS_CHANGE_TAB = 'DEVIATIONS_DETAILS_CHANGE_TAB';

export const DEVIATIONS_STATISTICS_CHANGE_FORM_FIELD_VALUES = 'DEVIATIONS_STATISTICS_CHANGE_FORM_FIELD_VALUES';
export const DEVIATIONS_STATISTICS_LOAD_PAGE = 'DEVIATIONS_STATISTICS_LOAD_PAGE';
export const DEVIATIONS_STATISTICS_LOAD_METADATA = 'DEVIATIONS_STATISTICS_LOAD_METADATA';
export const DEVIATIONS_STATISTICS_CHANGE_TAB = 'DEVIATIONS_STATISTICS_CHANGE_TAB';

export const DEVIATIONS_TOTAL_CHANGE_TAB = 'DEVIATIONS_TOTAL_CHANGE_TAB';
export const DEVIATIONS_TOTAL_CHANGE_FORM_FIELD_VALUES = 'DEVIATIONS_TOTAL_CHANGE_FORM_FIELD_VALUES';
export const DEVIATIONS_TOTAL_START_LOADING = 'DEVIATIONS_TOTAL_START_LOADING';
export const DEVIATIONS_TOTAL_LOAD_DATA = 'DEVIATIONS_TOTAL_LOAD_DATA';
export const DEVIATIONS_TOTAL_LOAD_METADATA = 'DEVIATIONS_TOTAL_LOAD_METADATA';

export const DEVIATIONS_CHART_CHANGE_FORM_FIELD_VALUES = 'DEVIATIONS_CHART_CHANGE_FORM_FIELD_VALUES';
