export const TOGGLE_MENU = 'TOGGLE_MENU';
export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const MESSAGE_HIDE = 'MESSAGE_HIDE';
export const ERROR_SHOW = 'ERROR_SHOW';
export const CLEAR_LOADED_DATA = 'CLEAR_LOADED_DATA';
export const LOCK_TOGGLE = 'LOCK_TOGGLE';

export const REVOKE = 'REVOKE';

export const USER_LOAD_INFO = 'USER_LOAD_INFO';

export const DEVIATIONS_BROWSE_CHANGE_FORM_FIELD_VALUES = 'DEVIATIONS_BROWSE_CHANGE_FORM_FIELD_VALUES';
export const DEVIATIONS_BROWSE_LOAD_PAGE = 'DEVIATIONS_BROWSE_LOAD_PAGE';

export const DEVIATIONS_DETAILS_SET_ID = 'DEVIATIONS_DETAILS_SET_ID';
export const DEVIATIONS_DETAILS_SET_DATA_LOCK_TOGGLE = 'DEVIATIONS_DETAILS_SET_DATA_LOCK_TOGGLE';
export const DEVIATIONS_DETAILS_SET_DATA = 'DEVIATIONS_DETAILS_SET_DATA';
export const DEVIATIONS_DETAILS_CHANGE_FORM_FIELD_VALUES = 'DEVIATIONS_DETAILS_CHANGE_FORM_FIELD_VALUES';
export const DEVIATIONS_DETAILS_CHANGE_TAB = 'DEVIATIONS_DETAILS_CHANGE_TAB';

export const DEVIATIONS_STATISTICS_CHANGE_TITLE = 'DEVIATIONS_STATISTICS_CHANGE_TITLE';
export const DEVIATIONS_STATISTICS_CHANGE_PUBLISHED_TIME_BEGIN = 'DEVIATIONS_STATISTICS_CHANGE_PUBLISHED_TIME_BEGIN';
export const DEVIATIONS_STATISTICS_CHANGE_PUBLISHED_TIME_END = 'DEVIATIONS_STATISTICS_CHANGE_PUBLISHED_TIME_END';
export const DEVIATIONS_STATISTICS_CHANGE_SORT_FIELD = 'DEVIATIONS_STATISTICS_CHANGE_SORT_FIELD';
export const DEVIATIONS_STATISTICS_CHANGE_SORT_ORDER = 'DEVIATIONS_STATISTICS_CHANGE_SORT_ORDER';
export const DEVIATIONS_STATISTICS_CHANGE_TIMESTAMP_BEGIN = 'DEVIATIONS_STATISTICS_CHANGE_TIMESTAMP_BEGIN';
export const DEVIATIONS_STATISTICS_CHANGE_TIMESTAMP_END = 'DEVIATIONS_STATISTICS_CHANGE_TIMESTAMP_END';
export const DEVIATIONS_STATISTICS_CHANGE_CHART_TYPE = 'DEVIATIONS_STATISTICS_CHANGE_CHART_TYPE';
export const DEVIATIONS_STATISTICS_LOAD_PAGE = 'DEVIATIONS_STATISTICS_LOAD_PAGE';

export const DEVIATIONS_CHART_CHANGE_FORM_FIELD_VALUES = 'DEVIATIONS_CHART_CHANGE_FORM_FIELD_VALUES';
