export const ROUND_PERIOD_NO_ROUND = 1;
export const ROUND_PERIOD_1_MINUTE = 60 * 1000;
export const ROUND_PERIOD_10_MINUTES = 10 * ROUND_PERIOD_1_MINUTE;
export const ROUND_PERIOD_1_HOUR = 60 * ROUND_PERIOD_1_MINUTE;
export const ROUND_PERIOD_4_HOURS = 4 * ROUND_PERIOD_1_HOUR;
export const ROUND_PERIOD_12_HOURS = 12 * ROUND_PERIOD_1_HOUR;
export const ROUND_PERIOD_1_DAY = 24 * ROUND_PERIOD_1_HOUR;
export const ROUND_PERIOD_7_DAYS = 7 * ROUND_PERIOD_1_DAY;
export const ROUND_PERIOD_10_DAYS = 10 * ROUND_PERIOD_1_DAY;
export const ROUND_PERIOD_30_DAYS = 30 * ROUND_PERIOD_1_DAY;

export const roundPeriodOptions = [
  [ROUND_PERIOD_NO_ROUND, 'No rounding'],
  [ROUND_PERIOD_1_MINUTE, '1 minute'],
  [ROUND_PERIOD_10_MINUTES, '10 minutes'],
  [ROUND_PERIOD_1_HOUR, '1 hour'],
  [ROUND_PERIOD_4_HOURS, '4 hours'],
  [ROUND_PERIOD_12_HOURS, '12 hours'],
  [ROUND_PERIOD_1_DAY, '1 day'],
  [ROUND_PERIOD_7_DAYS, '7 days'],
  [ROUND_PERIOD_10_DAYS, '10 days'],
  [ROUND_PERIOD_30_DAYS, '30 days'],
];
